# Generated by Django 3.2.13 on 2023-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='chart2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=255)),
                ('pulse', models.FloatField(default=0)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
