# Generated by Django 3.2.13 on 2023-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Department',
            field=models.CharField(default='OPD', max_length=50),
        ),
    ]
